### ISSUE TITLE
VXRD: PXRD Plot & Warnings

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/PyXtal#147]
## Steps to reproduce
1. Run VXRD Flask web app locally following [instructions here](https://github.com/qzhu2017/PyXtal/tree/master/flask).
2. On the ***Individual*** page, upload any valid .CIF or .POSCAR as your "Input File" (e.g., test files in `PyXtal\flask\instance\uploads`), then hit the **Visualize** button.

## Example result
![PXRD_Cl4Na4](https://user-images.githubusercontent.com/51060809/121287021-9f1b9780-c895-11eb-94ea-eb4fe617f550.png)

### When using .CIF as input
```bash
127.0.0.1 - - [08/Jun/2021 19:31:33] "GET /individual HTTP/1.1" 200 -
/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/ase/io/cif.py:402: UserWarning: crystal system 'cubic' is not interpreted for space group Spacegroup(225, setting=1). This may result in wrong setting!
  warnings.warn(
/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/ase/utils/__init__.py:41: FutureWarning: Please use atoms.cell.reciprocal()
  warnings.warn(warning)
127.0.0.1 - - [08/Jun/2021 19:31:45] "POST /individual HTTP/1.1" 200 -
/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/ase/io/cif.py:402: UserWarning:

crystal system 'cubic' is not interpreted for space group Spacegroup(225, setting=1). This may result in wrong setting!
```

### When using .POSCAR as input
```bash
127.0.0.1 - - [08/Jun/2021 19:31:51] "GET /struct/cif HTTP/1.1" 200 -
/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/ase/utils/__init__.py:41: FutureWarning:

Please use atoms.cell.reciprocal()
```

**Comment by qzhu2017** [comment]
The first warning has been resolved. The 2nd one should be okay.

**Comment by sabaronett** [comment]
@qzhu2017, are you sure the individual plots look correct? I'm still getting the following for any structure I submit (like the example above):
![image](https://user-images.githubusercontent.com/51060809/122805175-a0799680-d27d-11eb-8638-64c15aab1261.png)
